apiVersion: v1
kind: ReplicaSet
metadata:
 name: replicaset-demo
spec:
 replicas: 4
 selector:
   matchLabels:
     tier: front-end-web-app
 template:
   metadata:
     labels:
       tier: front-end-web-app
   spec:
     containers:
     - name: nginx 
       image: nginx
