apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
      workload: ecommerce
  template:
    metadata:
      labels:
        app: orders
        workload: ecommerce
    spec:
      containers:
      - name: orders
        image: 528757830112.dkr.ecr.ap-south-1.amazonaws.com/order
        ports:
        - containerPort: 3002
