apiVersion: v1
kind: Service
metadata:
  name: products-service
#  namespace: ecommerce
spec:
  selector:
    app: products
  type: NodePort
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
